dist: trusty
language: node_js
node_js:
  - 10.14.1
cache: yarn
git:
  depth: false
branches:
  only:
    - develop
    - master
    - "/^feature\\/.*$/"
    - "/^hotfix\\/.*$/"
    - "/^release\\/.*$/"
    - "/^doc\\/.*$/"
    - "/^epic\\/.*$/"
script: ./build.sh
deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/publish-builds.sh
  on:
    branch: develop
notifications:
  email:
    on_failure: always
    on_success: change
addons:
  chrome: stable
